'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:2.0.50727.8745
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Dieser Quellcode wurde automatisch generiert von xsd, Version=2.0.50727.3038.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.loc.gov/MARC21/slim"),  _
 System.Xml.Serialization.XmlRootAttribute("record", [Namespace]:="http://www.loc.gov/MARC21/slim", IsNullable:=true)>  _
Partial Public Class recordType
    
    Private leaderField As leaderFieldType
    
    Private controlfieldField() As controlFieldType
    
    Private datafieldField() As dataFieldType
    
    Private typeField As recordTypeType
    
    Private typeFieldSpecified As Boolean
    
    Private idField As String
    
    '''<remarks/>
    Public Property leader() As leaderFieldType
        Get
            Return Me.leaderField
        End Get
        Set
            Me.leaderField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("controlfield")>  _
    Public Property controlfield() As controlFieldType()
        Get
            Return Me.controlfieldField
        End Get
        Set
            Me.controlfieldField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("datafield")>  _
    Public Property datafield() As dataFieldType()
        Get
            Return Me.datafieldField
        End Get
        Set
            Me.datafieldField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property type() As recordTypeType
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property typeSpecified() As Boolean
        Get
            Return Me.typeFieldSpecified
        End Get
        Set
            Me.typeFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.loc.gov/MARC21/slim")>  _
Partial Public Class leaderFieldType
    
    Private idField As String
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.loc.gov/MARC21/slim")>  _
Partial Public Class subfieldatafieldType
    
    Private idField As String
    
    Private codeField As String
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property code() As String
        Get
            Return Me.codeField
        End Get
        Set
            Me.codeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.loc.gov/MARC21/slim")>  _
Partial Public Class dataFieldType
    
    Private subfieldField() As subfieldatafieldType
    
    Private idField As String
    
    Private tagField As String
    
    Private ind1Field As String
    
    Private ind2Field As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("subfield")>  _
    Public Property subfield() As subfieldatafieldType()
        Get
            Return Me.subfieldField
        End Get
        Set
            Me.subfieldField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property tag() As String
        Get
            Return Me.tagField
        End Get
        Set
            Me.tagField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property ind1() As String
        Get
            Return Me.ind1Field
        End Get
        Set
            Me.ind1Field = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property ind2() As String
        Get
            Return Me.ind2Field
        End Get
        Set
            Me.ind2Field = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.loc.gov/MARC21/slim")>  _
Partial Public Class controlFieldType
    
    Private idField As String
    
    Private tagField As String
    
    Private valueField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property tag() As String
        Get
            Return Me.tagField
        End Get
        Set
            Me.tagField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlTextAttribute()>  _
    Public Property Value() As String
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.loc.gov/MARC21/slim")>  _
Public Enum recordTypeType
    
    '''<remarks/>
    Bibliographic
    
    '''<remarks/>
    Authority
    
    '''<remarks/>
    Holdings
    
    '''<remarks/>
    Classification
    
    '''<remarks/>
    Community
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.loc.gov/MARC21/slim"),  _
 System.Xml.Serialization.XmlRootAttribute("collection", [Namespace]:="http://www.loc.gov/MARC21/slim", IsNullable:=true)>  _
Partial Public Class collectionType
    
    Private recordField() As recordType
    
    Private idField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("record", IsNullable:=true)>  _
    Public Property record() As recordType()
        Get
            Return Me.recordField
        End Get
        Set
            Me.recordField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
End Class


Partial Public Class NewDataSet
End Class
